---
title: "Which p-values can you expect?"
runtime: shiny
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(pwr)
knitr::opts_chunk$set(echo = TRUE)

#Disable scientific notation (1.05e10)
options(scipen=999)
set.seed(23)
```

## Set variables

```{r init_variables}
fluidRow(
    #number of simulated experiments
    column(3, numericInput("nSims", "Number of simulations",value=100000, min=1, step=1)),
    #Mean IQ score in the sample (will be compared with 100 in a one-sample t-test)
    column(2, numericInput("M", "Mean IQ in sample", value=106, min=1, step=1)),
    #set sample size
    column(2, numericInput("n", "Sample size", value=26, min=1, step=1)),
    #SD of the simulated data
    column(3, numericInput("SD", "StdDev of simulations", value=15, min=0)),
    #With a mean difference of 6, and SD of 15, and a sample size of 26, the test has 50% power)
    #Set your own mu
    column(2, numericInput("mu", "Hypothesis mean", value=100, min=0))
)

actionButton("button", label="Run simulation", icon("refresh"))

run_simulation <- eventReactive(input$button, {
    withProgress(message = "running simulation", value = 0, {
        #Run simulation
        nSims <- input$nSims
        #set up empty variable to store all simulated p-values
        p <- numeric(nSims)
        n <- input$n
        M <- input$M
        SD <- input$SD
        mu <- input$mu
        #for each simulated experiment
        for(i in 1:nSims){
            if(i%%round(nSims/10) == 0){incProgress(1/10)}
            #Simulate data with specified mean, standard deviation, and sample size
            x <- rnorm(n = n, mean = M, sd = SD)
            #perform the t-test against mu (set to value you want to test against)
            z <- t.test(x, mu=mu)
            #get the p-value and store it
            p[i] <- z$p.value
        }
    })

    power <- pwr.t.test(
        d=(input$M-100)/input$SD,
        n=input$n,
        sig.level=0.05,
        type="one.sample",
        alternative="two.sided"
    )$power #determines M when power > 0. When power = 0, will set  M = 100.

    list(p=p, nSims=nSims, power=power)
})
```

## {.tabset}

### Simulated power

```{r check_power}
#Check power by summing significant p-values and dividing by number of simulations
renderText({
    if(input$button == 0){print("Awaiting simulation...")}
    else{
        sim <- run_simulation()
        print(
            paste0(
                "The power as determined by the simulations is: ",
                (sum(sim$p < 0.05)/sim$nSims)
            )
        )
    }
})
```

### Calcuclated power

```{r calculate_power}
renderText({
    if(input$button == 0){print("Awaiting simulation...")}
})

numericInput("bars", "Number of histogram bars", value=20, min=1, step=1)

renderPlot({
    sim <- run_simulation()
    power <- sim$power
    g <- ggplot(data.table(p=sim$p), aes(x=p)) +
        geom_histogram(bins=input$bars) +
        theme_bw() +
        labs(
            x = "P-values",
            y = "Number of P-values",
            title = paste0(
                "P-value Distribution with ",
                round(power*100, 1),
                "% power"
            )
        )
    g
})
```

Daniel Lakens, 2016. 
This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. https://creativecommons.org/licenses/by-nc-sa/4.0/