---
title: "Likelihoods"
runtime: shiny
output: 
    html_document:
        code_folding: hide
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(shiny)
knitr::opts_chunk$set(echo = TRUE)
```

```{r variables}
theta <- seq(0,1,len=100) #create theta variable, from 0 to 1
fluidRow(
    #set total trials
    column(3, numericInput("n", "Trials", value=10, min=1, step=1)),
    #set successes
    column(3, numericInput("x", "Successes", value=8, min=1, step=1)),
    #specify one hypothesis you want to compare with the likihood ratio
    column(3, numericInput("H0", "H0", value=0.5, min=0, max=1)),
    #specify another hypothesis you want to compare with the likihood ratio
    column(3, numericInput("H1", "H1", value=0.05, min=0, max=1))
)

likelihood <- reactive({
    #Find the likelihood value for each hypothesis
    l0 <- dbinom(input$x, input$n, input$H0)
    l1 <- dbinom(input$x, input$n, input$H1)
    # Calculate likelihood values for each theta
    likelihood_data <- data.table(
        theta = theta,
        likelihood = dbinom(input$x, input$n, theta)
    )
    list(l0 = l0, l1 = l1, likelihood_data = likelihood_data)
})
```

```{r plot_likelihoods, eval=FALSE}
#This section is redundant given the next section
#plot likelihood curve
output$likelihood_plot <- shiny::renderPlot({
    #create likelihood function
    l <- likelihood()
    g <- ggplot(l$likelihood_data, aes(x=theta, y=likelihood)) +
        geom_line() +
        labs(x=expression(theta), y="Likelihood", title="Likelihood curve") +
        theme_bw()
    g
})

shiny::plotOutput("likelihood_plot")
```

## Calculate likelihood ratio

```{r calculate_likelihood_ratio}
output$plot_calculate_likelihood_ratio <- shiny::renderPlot({
    l <- likelihood()
    bound <- data.table(
        x = c(max(input$H0, input$H1) + 0.1, max(input$H0, input$H1) + 0.1),
        y = c(l$l0, l$l1),
        x0 = c(input$H0, max(input$H0, input$H1) + 0.1),
        y0 = c(l$l0, l$l0),
        x1 = c(input$H1, max(input$H0, input$H1) + 0.1),
        y1 = c(l$l1, l$l1)
    )
    g <- ggplot(l$likelihood_data, aes(x=theta, y=likelihood)) +
        geom_line() +
        geom_point(x=input$H0, y=l$l0, col="red") +
        geom_point(x=input$H1, y=l$l1, col="red") +
        geom_line(data=bound, aes(x=x, y=y), col="red") +
        geom_line(data=bound, aes(x=x0, y=y0), col="red", linetype="dashed") +
        geom_line(data=bound, aes(x=x1, y=y1), col="red", linetype="dashed") +
        theme_bw() +
        labs(
            x="Theta",
            y="Likelihood",
            title=paste(
                'Likelihood Ratio H0/H1:', round(l$l0/l$l1, 2),
                "\nLikelihood Ratio H1/H0:", round(l$l1/l$l0, 2)
            )
        )
    g
})

shiny::plotOutput("plot_calculate_likelihood_ratio")
```


Daniel Lakens, 2016. 
This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License. https://creativecommons.org/licenses/by-nc-sa/4.0/